sudo: required
dist: trusty
language: node_js
node_js:
- 6
before_install:
- openssl aes-256-cbc -K $encrypted_1a17a39c3439_key -iv $encrypted_1a17a39c3439_iv
  -in win10bash.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 66.112.221.142\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install
script:
- npm run build
after_success:
- cd ./build && tar -jcf busbus-react.tar.bz2 *    # 打包并压缩代码
- scp -P 29581 busbus-react.tar.bz2 root@66.112.221.142:/root/work/www
- ssh -p 29581 root@66.112.221.142 'cd /root/work/www && tar -jxf busbus-react.tar.bz2 -C busbus-react'

